### ISSUE TITLE
$provide not explicit listed

### ISSUE THREAD

**Issue by DevTrong** [Izhaki/ngTranscludeMod#1]
.config of module ngTranscludeMod uses $provide

the dependency $provide (to be injected) is not explicitly listed.

**Comment by Izhaki** [comment]
Hmmm...

What issue does it cause? I struggle to find any code examples that actually inject `$provide` in config blocks (for example, see [this](https://github.com/angular/angular.js/wiki/Understanding-Dependency-Injection)). But this blog explain [why it could fail](http://blog.jorgenschaefer.de/2014/04/the-angularjs-module-system.html). Is this your case?

**Comment by DevTrong** [comment]
With Angular 1.3 you can enable "ng-strict-di" mode [here](https://docs.angularjs.org/api/ng/directive/ngApp). 

My app fails to start because of that missing dependency list.

**Comment by Izhaki** [comment]
OK, 

Before I update the library, could you please confirm this solves it:

```
.config( ["$provide", function ($provide) { ... }] );
```

Thanks

**Comment by DevTrong** [comment]
Yes! Thank you! :+1:

**Comment by Izhaki** [comment]
Updated!
